"""
Custom prompt generator component for job4u application.
Generates custom GPT instructions based on job analysis.
"""

import json
from typing import Dict, Any, Tuple
from loguru import logger

from ..utils.config import Config
from ..llm_client.base_client import BaseLLMClient


class CustomPromptGenerator:
    """
    Generates custom GPT instructions for interview preparation.
    """
    
    def __init__(self, config: Config, llm_client: BaseLLMClient):
        """
        Initialize the custom prompt generator.
        
        Args:
            config: Configuration instance
            llm_client: LLM client for generating prompts
        """
        self.config = config
        self.llm_client = llm_client
        logger.info("🔧 Custom prompt generator initialized successfully")
    
    def generate_instructions(self, job_analysis: Dict[str, Any]) -> Tuple[str, bool]:
        """
        Generate custom GPT instructions based on job analysis.
        
        Args:
            job_analysis: The analyzed job data
            
        Returns:
            Tuple of (instructions_text, success_status)
        """
        try:
            logger.info("🔍 Generating custom GPT instructions")
            
            # Use the LLM client to generate instructions
            instructions, success = self.llm_client.generate_custom_gpt_instructions(job_analysis)
            
            if success:
                logger.info("✅ Custom GPT instructions generated successfully")
                return instructions, True
            else:
                logger.error("❌ Failed to generate custom GPT instructions")
                return instructions, False
                
        except Exception as e:
            error_msg = f"Custom prompt generation failed: {str(e)}"
            logger.error(error_msg)
            return error_msg, False
    
    def validate_instructions(self, instructions: str) -> bool:
        """
        Validate that the generated instructions are properly formatted.
        
        Args:
            instructions: The generated instructions to validate
            
        Returns:
            True if valid, False otherwise
        """
        try:
            # Check if it's valid Markdown
            if not instructions.strip():
                return False
            
            # Check for required sections
            required_sections = [
                "Your Goals",
                "Behavioral Style",
                "Additional Notes"
            ]
            
            for section in required_sections:
                if section not in instructions:
                    logger.warning(f"Missing required section: {section}")
                    return False
            
            return True
            
        except Exception as e:
            logger.error(f"Instructions validation failed: {e}")
            return False
    
    def format_instructions(self, instructions: str, job_analysis: Dict[str, Any]) -> str:
        """
        Format and enhance the generated instructions.
        
        Args:
            instructions: The raw generated instructions
            job_analysis: The job analysis data
            
        Returns:
            Formatted instructions
        """
        try:
            # Add header with job information
            header = f"""# Custom GPT Instructions for {job_analysis.get('role', 'Position')} at {job_analysis.get('company', 'Company')}

**Role:** {job_analysis.get('role', 'N/A')}
**Location:** {job_analysis.get('location', 'N/A')}
**Job Link:** {job_analysis.get('job_link', 'N/A')}

---

"""
            
            formatted_instructions = header + instructions
            
            # Add footer with usage notes
            footer = """

---

**Usage Notes:**
- Copy and paste these instructions into a new Custom GPT
- Customize further based on your specific needs
- Test the GPT with sample questions before using in interviews
- Update instructions as you learn more about the company/role

**Generated by:** Job4U Interview Preparation Pipeline
"""
            
            return formatted_instructions + footer
            
        except Exception as e:
            logger.error(f"Instructions formatting failed: {e}")
            return instructions  # Return original if formatting fails
